account/urls.py
from django.urls import path
from . import views
app_name='account'
urlpatterns = [
    path('', views.singup, name='singup'),
    path('dentist/', views.dentist, name='dentist'),
    
    path('dentist-request/', views.dentistreq, name='dentistreq'),
    path('patient-dashboard/', views.customer, name='customer'),
    path('patient-review/', views.patient_review, name='patient_review'),
    path('patient-profile/', views.patient_profile, name='patient_profile'),
    path('patient-change-password/', views.patient_password, name='patient_password'),
] 

hm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import pre
# from exam import views as auth_view
admin.site.site_header = 'Dashboard'                    # default: "Django Administration"
admin.site.index_title = 'Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'Technologies Admin Panel' # default: "Django site admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    
    path('get-location-info/', pre.get_location_info, name='get_location_info'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='updatePW.html'), name="password_reset_confirm" ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="complete.html"), name= "password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
    path('', views.home, name='home'),
    path('find-dentist/', views.find_dentist, name='find_dentist'),
    path('gallery/', views.gallery, name='gallery'),
    path('dentist/<str:pk>/', views.find_dentist_d, name='find_dentist_d'),
    path('blogs/', views.blogs, name='blogs'),
    path('blogs/<str:pk>/', views.blogsd, name='blogsd'),
    path('contact/', views.contact, name='contact'),
    path('thank-you/', views.thankyou, name='thankyou'),
    path('sitemap.xml',views.sitemap, name='sitemap'),
    path('robots.txt',views.robots, name='robots'),
    path('all-usd/', views.all_usd, name='all_usd'),
    path('search-all-usd/', views.search_all_usd, name='search_all_usd'),
    path('receive_location/', views.receive_location, name='receive_location'),
] 

account/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
# Create your models here.
class Location(models.Model):
    state = models.CharField(max_length=300)
    short_code =  models.CharField(max_length=300)

    def __str__(self):
        return self.state



class City(models.Model):
    state = models.ForeignKey(Location, on_delete=models.CASCADE)    
    city = models.CharField(max_length=300)
    def __str__(self):
        return str(self.city)

    def countdr(self):
        return Dentist.objects.filter(city=self.id).count()

class Specializations(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Dentist(models.Model):
    h1  = models.CharField(max_length = 156)
    slug =models.CharField(max_length = 1256,blank=True, null=True)
    page_name = models.CharField(max_length = 1256,blank=True, null=True)
    keyword = models.CharField(max_length = 156,blank=True, null=True)
    description = models.CharField(max_length = 900,blank=True, null=True)
    seo_title = models.CharField(max_length = 156,blank=True, null=True)
    breadcrumb = models.CharField(max_length = 156,blank=True, null=True)
    canonical = models.CharField(max_length = 900,blank=True, null=True)
    og_type =models.CharField(max_length = 156,blank=True, null=True)
    og_card = models.CharField(max_length = 156,blank=True, null=True)
    og_site = models.CharField(max_length = 156,blank=True, null=True)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='User', blank=True, null=True )    

    city = models.ForeignKey(City, on_delete=models.CASCADE,blank=True, null=True)   
    state = models.CharField(max_length=300,blank=True, null=True)
      
    profile  = models.ImageField(upload_to="SEO",blank=True, null=True)
    
    name = models.CharField(max_length=300)
    title = models.CharField(max_length=300)
    sub_title = models.CharField(max_length=300,blank=True, null=True)
    email = models.CharField(max_length=300, blank=True, null=True)
    contact = models.CharField(max_length=300)
    bio = models.TextField(max_length=1300,blank=True, null=True)
    address = models.TextField(max_length = 15622, blank=True, null=True)
    education = RichTextUploadingField(blank=True, null=True)
    awards = RichTextUploadingField(blank=True, null=True)
    experience = RichTextUploadingField(blank=True, null=True)
    Coffee_table_book_Adimplant = models.CharField(max_length=300, default='1')
    Advance_zirconia  = models.CharField(max_length=300, default='1')
    Adaligner = models.CharField(max_length=300, default='1')
    USD_box = models.CharField(max_length=300, default='1')
    delivered_date = models.DateField( blank=True, null=True)



    

    specializations = models.ManyToManyField(Specializations, null=True, blank=True)
    iframe = models.TextField(max_length=1300,blank=True, null=True)

    status = models.BooleanField(default=False)
    treding = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)

    lat =  models.TextField(max_length=1300,blank=True, null=True)
    long =  models.TextField(max_length=1300,blank=True, null=True)
    schema = models.TextField(max_length = 15622, blank=True, null=True)


    Mon   = models.CharField(max_length=300, default='open',blank=True, null=True)
    Tue = models.CharField(max_length=300, default='open',blank=True, null=True)
    Wed = models.CharField(max_length=300, default='open',blank=True, null=True)
    Thu = models.CharField(max_length=300, default='open',blank=True, null=True)
    Fri = models.CharField(max_length=300, default='open',blank=True, null=True)
    Sat = models.CharField(max_length=300, default='open',blank=True, null=True)
    Sun = models.CharField(max_length=300, default='close',blank=True, null=True)
    

    def __str__(self):
        return self.name

class Image(models.Model):
    dentist = models.ForeignKey(Dentist, on_delete=models.CASCADE)    
    image = models.ImageField(upload_to="Dentist")

class Rating(models.Model):
    dentist = models.ForeignKey(Dentist, on_delete=models.CASCADE)    
    star = models.CharField(max_length=300)
    said = models.TextField(max_length=1300)
    by =   models.CharField(max_length=300)
    date =  models.CharField(max_length=300)



class Category(models.Model):
    category = models.CharField(max_length = 156)
    def __str__(self):
        return self.category

class Tags(models.Model):
    tags = models.CharField(max_length = 156)
    def __str__(self):
        return self.tags    

class Author(models.Model):
    description = RichTextUploadingField()
    name = models.CharField(max_length = 156)
    position = models.CharField(max_length = 156)
    fb =models.CharField(max_length = 156,blank=True, null=True)
    insta = models.CharField(max_length = 156, blank=True, null=True)
    linkedin = models.CharField(max_length = 156, blank=True, null=True)
    image  = models.ImageField(upload_to="SEO")
    def __str__(self):
        return self.name     
               
# Create your models here.
class Blog(models.Model):
    status  = models.BooleanField(default=True)
    
    h1  = models.CharField(max_length = 156)
    slug =models.CharField(max_length = 1256,blank=True, null=True)
    page_name = models.CharField(max_length = 1256,blank=True, null=True)
    keyword = models.CharField(max_length = 156)
    description = models.CharField(max_length = 900)
    title = models.CharField(max_length = 156)
    breadcrumb = models.CharField(max_length = 156)
    canonical = models.CharField(max_length = 900)
    og_type =models.CharField(max_length = 156)
    og_card = models.CharField(max_length = 156)
    og_site = models.CharField(max_length = 156)
    image  = models.ImageField(upload_to="SEO")
    
    category = models.ManyToManyField(Category)
    tag  = models.ManyToManyField(Tags)
    updated  = models.DateField(auto_now=True)
    

    blog_banner_lg = models.ImageField(upload_to="Page Data", blank=True, null=True)
    blog_banner_sm = models.ImageField(upload_to="Page Data", blank=True, null=True)
    
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    published  = models.DateField()
    content = RichTextUploadingField()
    active = True
    edits = RichTextUploadingField( blank=True, null=True)
    
    
    def __str__(self):
        return self.h1


class Team(models.Model):   
    image  = models.ImageField(upload_to="SEO")
    name = models.CharField(max_length = 156)
    position = models.CharField(max_length = 156)
    fb = models.CharField(max_length = 156)
    insta = models.CharField(max_length = 156)
    twitter = models.CharField(max_length = 156)
    youtube = models.CharField(max_length = 156)

    def __str__(self):
        return self.name



class Testimonials(models.Model):   
    image  = models.ImageField(upload_to="SEO")
    name = models.CharField(max_length = 156)
    position = models.CharField(max_length = 156)
    review = models.TextField()
 
    def __str__(self):
        return self.name
   

class Gallery(models.Model):   
    image  = models.ImageField(upload_to="SEO")
    
 
    def __str__(self):
        return str(self.id)

class Contact(models.Model):
    name =models.CharField(max_length = 1256,blank=True, null=True)
    email = models.CharField(max_length = 1256,blank=True, null=True)
    phone = models.CharField(max_length = 156)
    subject = models.CharField(max_length = 156)
    message =RichTextUploadingField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
        
        

class UserSubmission(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    agree_to_terms = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    
    
    
    
    
     

account/forms.py
from django import forms
from .models import *
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields= '__all__'
        
        
        
class UserSubmissionForm(forms.ModelForm):
    class Meta:
        model = UserSubmission
        fields = ['first_name', 'last_name', 'phone', 'email', 'agree_to_terms']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control sf-form-control cool', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control sf-form-control cool', 'placeholder': 'Last Name'}),
            'phone': forms.TextInput(attrs={'class': 'form-control sf-form-control cool', 'placeholder': 'Phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control sf-form-control cool', 'placeholder': 'Email'}),
            'agree_to_terms': forms.CheckboxInput(attrs={'id': 'td33'}),
        }

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserSubmissionForm  
from .models import UserSubmission
from django.contrib import messages 

# Create your views here.
def singup(request):
    context = {

    }
    return render(request, 'singup.html', context)



def dentist(request):
    if request.method == 'POST':
        form = UserSubmissionForm(request.POST)
        if form.is_valid():
            # Save the form data to the database
            user_submission = form.save()

            # Create a success message to display as a popup
            messages.success(request, f"Form submitted successfully! Thank you, {user_submission.first_name} {user_submission.last_name}.")

            # Redirect to the Thank You page
            return redirect('home:thankyou')  # Assuming 'home:thankyou' is the URL for the Thank You page
        else:
            # Handle form errors
            return render(request, 'request.html', {'form': form, 'error_message': 'Please correct the errors below.'})
    else:
        form = UserSubmissionForm()

    context = {
        'form': form,
    }
    return render(request, 'request.html', context)
    
    
    
def dentistreq(request):
    if request.method == 'POST':
        form = UserSubmissionForm(request.POST)
        if form.is_valid():
            # Save the form data to the database
            user_submission = form.save()

            # Create a success message to display as a popup
            messages.success(request, f"Form submitted successfully! Thank you, {user_submission.first_name} {user_submission.last_name}.")

            # Redirect to the Thank You page
            return redirect('home:thankyou')  # Assuming 'home:thankyou' is the URL for the Thank You page
        else:
            # Handle form errors
            return render(request, 'doctorreq.html', {'form': form, 'error_message': 'Please correct the errors below.'})
    else:
        form = UserSubmissionForm()

    context = {
        'form': form,
    }
    return render(request, 'doctorreq.html', context)


def customer(request):
    context = {

    }
    return render(request, 'customer.html', context)



def patient_review(request):
    context = {

    }
    return render(request, 'patient_review.html', context)

def patient_password(request):
    context = {

    }
    return render(request, 'patient_password.html', context)

def patient_profile(request):
    context = {

    }
    return render(request, 'patient_profile.html', context)

account/templates/customer.html
{% extends 'base2.html' %}
{% load static %}

{% block header %}

{% endblock header %}

{% block css %}
    
{% endblock css %}
    


{% block body %}
   
<!-- LOADING AREA START ===== -->
<div class="loading-area">
    <div class="loading-box"></div>
    <div class="loading-pic">
        <div class="cssload-wrap">
            <div class="cssload-container">
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
        </div>
        </div>
    </div>
</div>
<!-- LOADING AREA  END ====== -->

	<div class="page-wraper cus-account-wrap">
    
        <header id="header-admin-wrap" class="header-admin-fixed">
        
            <!-- Header Start -->
            <div id="header-admin">
                <div class="container">
                    
                    <!-- Left Side Content -->
                    <div class="header-left">
                        <div class="cus-account-logo">
                            <a href="{% url 'home:home' %}">
                                <img src="{% static 'logo.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- Left Side Content End -->
                    
                    <!-- Right Side Content -->
                    <div class="header-right">
                        
                        <ul class="header-widget-wrap">
                            
                            <li class="header-widget">
                                <div class="aon-admin-messange sf-toogle-btn">
                                    <span class="feather-user-pic"><img src="{% static 'images/user.jpg' %}" alt=""/></span>
                                </div>
                                <div class="ws-toggle-popup popup-tabs-wrap-section user-welcome-area">
                                    <div class="popup-tabs-head d-flex justify-content-between align-items-center">
                                        <div class="popup-tabHead-left"><h5 class="m-a0">David Wood</h5></div>
                                    </div>
                                    <ul class="user-welcome-list">
                                        <li><a href="#"><i class="feather-sliders"></i> Dashboard</a></li>
                                     
                                        <li><a href="#"><i class="feather-settings"></i> Profile</a></li>
                                        <li><a href="#"><i class="feather-log-out"></i> Log Out</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!-- Right Side Content End -->
        
                </div>
            </div>
            <!-- Header End -->
        
        </header>
        
        
    	
        <!-- Page Content Holder -->
        <div id="content">
            
            <div class="cus-top-nav">
                
                <div class="container">
    
                    <ul class="cus-nav row">
                        <li class="col active"><a href="{% url 'account:customer' %}">Appointments</a></li>
                        <li class="col"><a href="{% url 'account:patient_review' %}">My Feedback</a></li>
                        <li class="col"><a href="{% url 'account:patient_profile' %}">View/Edit Profile</a></li>
                        <li class="col"><a href="{% url 'account:patient_password' %}">Change Password</a></li>
                    </ul>
                </div>
                    
            </div>

            <div class="content-admin-main">
                
                
            	<div class="aon-admin-heading">
                	<h3>Appointments</h3>
                </div>  
                
                <div class="sf-appoi-row">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="sf-appoi-first d-flex align-items-center">
                            <div class="sf-appoi-user">
                                <img src="{% static 'images/testimonial-img/img1.png' %}" alt="">
                            </div>
                            <div class="sf-appoi-info">
                                <h4><a href="#">Lussa Smith</a></h4>
                                
                            </div>
                            <div class="aon-date-box">
                                <strong>21</strong>
                                <span>MAR</span>
                            </div>
                        </div>
                        <div class="sf-appoi-second">
                            <i class="fa fa-calendar-o"></i> Tuesday, <i class="fa fa-clock-o"></i> 05:40 PM
                        </div>
                        <div class="sf-appoi-second">
                            <span class="btn-pending">Pending</span>
                        </div>                        
                        
                        <div class="sf-appoi-third">
                            <div class="dropdown action-dropdown dropdown-left">
                                <button  type="button" class="action-button btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-ellipsis-v"></i>
                                </button> 
                                <ul class="dropdown-menu" >
                                    <li><a class="dropdown-item" href="javascript:;"><i class="feather-calendar"></i> Book Again</a></li>
                                    <li><a class="dropdown-item" href="javascript:;"><i class="feather-trash"></i> Cancel</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
               

 
            </div>
            
    	</div>

 </div>       


{% endblock body %}
    


{% block js %}

{% endblock js %}
    

account/templates/patient_password.html
{% extends 'base2.html' %}
{% load static %}

{% block header %}

{% endblock header %}

{% block css %}
    
{% endblock css %}
    


{% block body %}
   
<!-- LOADING AREA START ===== -->
<div class="loading-area">
    <div class="loading-box"></div>
    <div class="loading-pic">
        <div class="cssload-wrap">
            <div class="cssload-container">
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
            <span class="cssload-dots"></span>
        </div>
        </div>
    </div>
</div>
<!-- LOADING AREA  END ====== -->

	<div class="page-wraper cus-account-wrap">
    
        <header id="header-admin-wrap" class="header-admin-fixed">
        
            <!-- Header Start -->
            <div id="header-admin">
                <div class="container">
                    
                    <!-- Left Side Content -->
                    <div class="header-left">
                        <div class="cus-account-logo">
                            <a href="{% url 'home:home' %}">
                                <img src="{% static 'logo.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- Left Side Content End -->
                    
                    <!-- Right Side Content -->
                    <div class="header-right">
                        
                        <ul class="header-widget-wrap">
                            
                            <li class="header-widget">
                                <div class="aon-admin-messange sf-toogle-btn">
                                    <span class="feather-user-pic"><img src="{% static 'images/user.jpg' %}" alt=""/></span>
                                </div>
                                <div class="ws-toggle-popup popup-tabs-wrap-section user-welcome-area">
                                    <div class="popup-tabs-head d-flex justify-content-between align-items-center">
                                        <div class="popup-tabHead-left"><h5 class="m-a0">David Wood</h5></div>
                                    </div>
                                    <ul class="user-welcome-list">
                                        <li><a href="#"><i class="feather-sliders"></i> Dashboard</a></li>
                                     
                                        <li><a href="#"><i class="feather-settings"></i> Profile</a></li>
                                        <li><a href="#"><i class="feather-log-out"></i> Log Out</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!-- Right Side Content End -->
        
                </div>
            </div>
            <!-- Header End -->
        
        </header>
        
        
    	
        <!-- Page Content Holder -->
        <div id="content">
            
            <div class="cus-top-nav">
                
                <div class="container">
    
                    <ul class="cus-nav row">
                        <li class="col "><a href="{% url 'account:customer' %}">Appointments</a></li>
                        <li class="col "><a href="{% url 'account:patient_review' %}">My Feedback</a></li>
                        <li class="col"><a href="{% url 'account:patient_profile' %}">View/Edit Profile</a></li>
                        <li class="col active"><a href="{% url 'account:patient_password' %}">Change Password</a></li>
                    </ul>
                </div>
                    
            </div>
            <div class="content-admin-main">
                
            	<div class="aon-admin-heading">
                	<h3>Change Password</h3>
                </div>  
                
                <div class="card aon-card cus-chan-pass-wrap">
                    <div class="card-body aon-card-body">
                        <div class="cus-chan-pass-form">
                            <div class="form-group">
                                <label>Current Password</label>
                                <div class="aon-inputicon-box"> 
                                    <input class="form-control sf-form-control" name="company_name" type="text">
                                    <i class="aon-input-icon fa fa-lock"></i>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>New Password</label>
                                <div class="aon-inputicon-box"> 
                                    <input class="form-control sf-form-control" name="company_name" type="text">
                                    <i class="aon-input-icon fa fa-lock"></i>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Confirm  Password</label>
                                <div class="aon-inputicon-box"> 
                                    <input class="form-control sf-form-control" name="company_name" type="text">
                                    <i class="aon-input-icon fa fa-lock"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                
                <div class="aon-admin-footer d-flex justify-content-between align-items-center">
                    <div class="aon-admin-footer-left">
                        <div class="alert alert-success" role="alert">This is a success alert—check it out!</div>
                    </div>
                    <div class="aon-admin-footer-right">
                        <button class="admin-button m-r10">Cancel</button>
                        <button class="admin-button">Save</button>
                    </div>
                </div>
 
            </div>


        </div>
            
    	</div>

 </div>       


{% endblock body %}
    


{% block js %}

{% endblock js %}
    