account/urls.py
from django.urls import path
from . import views
app_name='account'
urlpatterns = [
    path('', views.singup, name='singup'),
    path('dentist/', views.dentist, name='dentist'),
    
    path('dentist-request/', views.dentistreq, name='dentistreq'),
    path('patient-dashboard/', views.customer, name='customer'),
    path('patient-review/', views.patient_review, name='patient_review'),
    path('patient-profile/', views.patient_profile, name='patient_profile'),
    path('patient-change-password/', views.patient_password, name='patient_password'),
] 

hm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import pre
# from exam import views as auth_view
admin.site.site_header = 'Dashboard'                    # default: "Django Administration"
admin.site.index_title = 'Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'Technologies Admin Panel' # default: "Django site admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    
    path('get-location-info/', pre.get_location_info, name='get_location_info'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='updatePW.html'), name="password_reset_confirm" ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="complete.html"), name= "password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
    path('', views.home, name='home'),
    path('find-dentist/', views.find_dentist, name='find_dentist'),
    path('gallery/', views.gallery, name='gallery'),
    path('dentist/<str:pk>/', views.find_dentist_d, name='find_dentist_d'),
    path('blogs/', views.blogs, name='blogs'),
    path('blogs/<str:pk>/', views.blogsd, name='blogsd'),
    path('contact/', views.contact, name='contact'),
    path('thank-you/', views.thankyou, name='thankyou'),
    path('sitemap.xml',views.sitemap, name='sitemap'),
    path('robots.txt',views.robots, name='robots'),
    path('all-usd/', views.all_usd, name='all_usd'),
    path('search-all-usd/', views.search_all_usd, name='search_all_usd'),
    path('receive_location/', views.receive_location, name='receive_location'),
] 

templates/base2.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    {% load static %}
	<!-- META -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />    
    <meta name="description" content="" />
    
    <!-- FAVICONS ICON -->
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.png' %}" />
    
    <!-- PAGE TITLE HERE -->
    <title>Find Ultimate Smile Designers - By ADE</title>
    
    <!-- MOBILE SPECIFIC -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">	
    
    <!-- BOOTSTRAP STYLE SHEET -->
    <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- FONTAWESOME STYLE SHEET -->
    <link  href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Feather STYLE SHEET -->
    <link href="{% static 'css/feather.css' %}" rel="stylesheet">

    
    <!-- OWL CAROUSEL STYLE SHEET -->
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <!-- SLICK CAROUSEL STYLE SHEET -->
    <link href="{% static 'css/slick.min.css' %}" rel="stylesheet">
    <!-- SLICK STYLE SHEET -->
    <link href="{% static 'css/slick-theme.css' %}" rel="stylesheet">
    <!-- Custome scrollbar STYLE SHEET  -->
    <link href="{% static 'css/jquery.scrollbar.css' %}" rel="stylesheet">  
    <!-- DropZone STYLE SHEET  --> 
    <link href="{% static 'css/dropzone.css' %}" rel="stylesheet">       
    <!-- MAGNIFIC POPUP STYLE SHEET -->
    <link href="{% static 'css/magnific-popup.min.css' %}" rel="stylesheet">
    <!-- FLATICON STYLE SHEET -->
    <link href="{% static 'css/flaticon.min.css' %}" rel="stylesheet">
    <!-- Lc light box popup -->
    <link href="{% static 'css/lc_lightbox.css' %}" rel="stylesheet">     
    <!-- Price Range Slider -->
    <link href="{% static 'css/bootstrap-slider.min.css' %}" rel="stylesheet">
    <!-- Bootstrap-toggle -->
    <link href="{% static 'css/bootstrap4-toggle.min.css' %}" rel="stylesheet">
    <!-- Bootstrap-datatables -->
    <link href="{% static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <!-- Date-picker -->
    <link href="{% static 'css/date-picker.css' %}" rel="stylesheet">
    <!-- Full calendar -->
    <link href="{% static 'css/fullcalendar.min.css' %}" rel="stylesheet">   
    <!-- MAIN STYLE SHEET -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">   
    


</head>

<body>
    

    
	<div class="page-wraper">
     
   
    
        
        {% block body %}
            
        {% endblock body %}
            

        

       

 	</div>

    
    
<!-- JAVASCRIPT  FILES ========================================= --> 
<script  src="{% static 'js/jquery-3.6.0.min.js' %}"></script><!-- JQUERY.MIN JS -->
<script  src="{% static 'js/popper.min.js' %}"></script><!-- POPPER.MIN JS -->
<script  src="{% static 'js/bootstrap.min.js' %}"></script><!-- BOOTSTRAP.MIN JS -->
    
<script  src="{% static 'js/jquery.bootstrap-touchspin.js' %}"></script><!-- FORM JS -->
<script  src="{% static 'js/bootstrap-slider.min.js' %}"></script><!-- BOOTSTRAP Slider --> 
<script  src="{% static 'js/magnific-popup.min.js' %}"></script><!-- MAGNIFIC-POPUP JS -->
<script  src="{% static 'js/waypoints.min.js' %}"></script><!-- WAYPOINTS JS -->
<script  src="{% static 'js/counterup.min.js' %}"></script><!-- COUNTERUP JS -->
<script  src="{% static 'js/waypoints-sticky.min.js' %}"></script><!-- STICKY HEADER -->
<script  src="{% static 'js/isotope.pkgd.min.js' %}"></script><!-- MASONRY  -->
<script  src="{% static 'js/owl.carousel.min.js' %}"></script><!-- OWL  SLIDER  -->
<script  src="{% static 'js/slick.min.js' %}"></script><!-- Slick SLIDER  -->
<script  src="{% static 'js/theia-sticky-sidebar.js' %}"></script><!-- STICKY SIDEBAR  -->
<script  src="{% static 'js/jquery.scrollbar.min.js' %}"></script><!-- MY ACCOUNT LEFT PANEL SCROLLER -->
<script  src="{% static 'js/dropzone.js' %}"></script><!--IMAGE UPLOAD-->  
<script  src="{% static 'js/bootstrap4-toggle.min.js' %}"></script><!-- BOOTSTRAP TOOGLE-->
<script  src="{% static 'js/jquery.dataTables.min.js' %}"></script><!--DATA TABLE-->
<script  src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script><!-- DATA TABLE-->
<script  src="{% static 'js/lc_lightbox.lite.js' %}" ></script><!-- IMAGE POPUP -->
<script  src="{% static 'js/datepicker.min.js' %}"></script><!-- DATEPICKER -->
<script  src="{% static 'js/fullcalendar.min.js' %}"></script><!-- DATEPICKER -->
<script src="{% static 'js/recaptcha-api.js' %}"></script><!-- RECAPTCHA-->
<script  src="{% static 'js/custom.js' %}"></script><!-- CUSTOM FUCTIONS  -->

{% block js %}
    <!--Sweet alert after submit the request-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    {% if messages %}
        
        {% for ie in messages %}
            <script>
                Swal.fire({
                    position: "top-end",
                    icon: "{{ie.tags}}",
                    title: "{{ie.message}}",
                    showConfirmButton: false,
                    timer: 2500
                    });
            </script>
        {% endfor %}
            
    {% endif %}
    
{% endblock js %}
    


</body>

</html>

templates/header.html
{% load static %}

 <!-- HEADER START -->
 <header class="site-header header-style-2 mobile-sider-drawer-menu">
    <div class="sticky-header main-bar-wraper  navbar-expand-lg">
        <div class="main-bar">  
                            
            <div class="container clearfix" style="height: 59px;"> 
                <!--Logo section start-->
                <div class="logo-header">
                    <div class="logo-header-inner logo-header-one">
                        <a href="{% url 'home:home' %}">
                            <img class="logo-pic-one" src="{% static 'usdlog.png' %}" alt="usdlogo">
                            <img class="logo-pic-two" src="{% static 'usdlog.png' %}" alt="usdlogo">
                        </a>
                    </div>
                </div>  
                <!--Logo section End-->

                <!-- NAV Toggle Button -->
                <button id="mobile-side-drawer" data-target=".header-nav" data-toggle="collapse" type="button" class="navbar-toggler collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar icon-bar-first"></span>
                    <span class="icon-bar icon-bar-two"></span>
                    <span class="icon-bar icon-bar-three"></span>
                </button> 

                <!-- MAIN Vav -->
                <div class="nav-animation header-nav navbar-collapse collapse d-flex justify-content-center">
                    
                    <ul class=" nav navbar-nav">
                        
                        <li class="cool"><a href="{% url 'home:home' %}">Ultimate Smile Design 
                        </a>
                        </li> 
                        <li class="cool"><a href={% url 'home:search_all_usd' %}>Find Dentist</a>
                        </li> 
                        <li class="cool"><a href="{% url 'home:gallery' %}">Gallery</a>
                        </li> 
                        <li class="cool"><a href="{% url 'home:blogs' %}">Blogs</a>
                        </li>                                                                
                        <li class="cool"><a href="{% url 'home:contact' %}">Contact</a>
                                                   
                        </li> 
                
                    </ul>

                </div>
                
                <!-- Header Right Section-->
                <div class="extra-nav header-2-nav">
                    <div class="extra-cell">

                        <!--Sign up-->
                        
                        {% if user.is_authenticated %}
                        <a href="" class="site-button-link aon-btn-signup m-l20" >
                            <i class="feather-user"></i> Dashboard
                        </a>
                        <a href="" class="site-button-link aon-btn-signup m-l20" >
                            <i class="feather-lock"></i> Logout
                        </a>
                        <a href="{% url 'account:dentist' %}" class="site-button aon-add-listing m-l20" >
                            <i class="fa fa-map-marker"></i>
                         
                            {{city}}
                        </a> 
                        {% else %}
                        <!--<a href="{% url 'account:singup' %}" class="site-button-link aon-btn-signup m-l20" >-->
                        <!--    <i class="feather-user"></i> Sign In-->
                        <!--</a>-->
                        <!--Add Listing up-->
                        <a href="{% url 'account:dentist' %}" class="site-button aon-add-listing m-l20 bat">
                          <img src="{% static 'medical.png' %}" alt="For Patients" style="width: 20px; height: 20px;"> For Patients
                        </a>
                        <a href="https://dentist.ultimatesmiledesign.com/" target="_blank" class="site-button aon-add-listing m-l20 bat">
                           <img src="{% static 'doctor.png' %}" alt="For Dentist" style="width: 20px; height: 20px;"> For Dentist
                        </a>

                        {% endif %}

                        </div>
                        
                    </div>                            
            
            </div>    
        
        </div>
    </div>
</header>
<!-- HEADER END -->

<div class="d-none">
    <p id="demo"></p>
    {{city}} or
    {{state}}
</div>

templates/temp.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

{% endblock header %}

{% block css %}
    
{% endblock css %}
    


{% block body %}
   
<div class="page-wraper">
     
    
    <!-- CONTENT START -->
    <div class="page-content">

    
        <!-- Search Bar Home START -->
        <div class="aon-login-wrap d-flex">
             <div class="aon-login-left">
                 <div class="aon-login-heading">
                     <div class="aon-login-text">
                         Your Trust is Our Greatest Incentive!
                     </div>
                     <div class="aon-login-pic">
                         <img src={% static 'images/banner2/doctor.png' %}" alt=""/>
                     </div>
                 </div>
            </div>
             <div class="aon-login-right d-flex flex-wrap align-items-center">
                 <div class="aon-login-area">
                 <div class="col-md-12">
                     <div class="site-logo login-sign-logo">
                         <a href="index.html"><img src={% static 'images/logo-dark.png' %}" alt=""/></a>
                     </div>
                 </div>
                 <div class="col-md-12">
                     <div class="login-sign-head">
                         <strong>Welcome Back</strong>
                         <span>Welcome back! Please enter your details.</span>
                     </div>
                 </div>                       
                 
                <ul class="nav nav-pills mb-3 aon-custom-nav aon-login-sign-tabs calen-list-nav m-b30" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <div class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-one" role="tab" aria-selected="true">Login</div>
                    </li>
                    <li class="nav-item" role="presentation">
                        <div class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-two" role="tab" aria-selected="false">Register</div>
                    </li>
                </ul>
                <div class="tab-content" >
                    <div class="tab-pane fade show active" id="pills-one" role="tabpanel" aria-labelledby="pills-home-tab">
                        <form class="aon-login-form">
                         <div class="row">
                             <div class="col-md-12">
                                 <div class="form-group">
                                    <label>First Name</label>
                                    <div class="aon-inputicon-box"> 
                                        <input class="form-control sf-form-control" name="company_name" type="text">
                                        <i class="aon-input-icon fa fa-user"></i>
                                    </div>
                                 </div>
                             </div>
                             <div class="col-md-12">
                                 <div class="form-group">
                                    <label>Password</label>
                                    <div class="aon-inputicon-box"> 
                                        <input class="form-control sf-form-control" name="company_name" type="text">
                                        <i class="aon-input-icon fa fa-lock"></i>
                                    </div>
                                 </div>
                             </div>
                             <div class="col-md-12">
                                <div class="form-group d-flex aon-login-option justify-content-between">
                                    <div class="aon-login-opleft">
                                         <div class="checkbox sf-radio-checkbox">
                                            <input id="td2_2" name="abc" value="five" type="checkbox">
                                            <label for="td2_2">Keep me logged</label>
                                        </div>  
                                    </div>
                                    <div class="aon-login-opright">
                                        <a href="#">Forget Password</a>
                                    </div>
                                </div>
                             </div>
                             <div class="col-md-12">
                                <button type="submit" class="site-button w-100">Submit <i class="feather-arrow-right"></i> </button>
                             </div>
                         </div>
                     </form>
                    </div>
                    <div class="tab-pane fade" id="pills-two" role="tabpanel" aria-labelledby="pills-profile-tab">
                        <form class="aon-login-form">
                             <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label >First Name</label>
                                        <div class="aon-inputicon-box"> 
                                            <input class="form-control sf-form-control" name="First_Name" type="text" placeholder="First Name">
                                            <i class="aon-input-icon fa fa-user"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label >Last Name</label>
                                        <div class="aon-inputicon-box"> 
                                            <input class="form-control sf-form-control" name="company_name" type="password" placeholder="Last Name">
                                            <i class="aon-input-icon fa fa-user"></i>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label >Phone Number</label>
                                        <div class="aon-inputicon-box"> 
                                            <input class="form-control sf-form-control" name="Phone" type="password" placeholder="Phone">
                                            <i class="aon-input-icon fa fa-phone"></i>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label >Email Address</label>
                                        <div class="aon-inputicon-box"> 
                                            <input class="form-control sf-form-control" name="email" type="password" placeholder="Email">
                                            <i class="aon-input-icon fa fa-envelope-o"></i>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label >Password</label>
                                        <div class="aon-inputicon-box"> 
                                            <input class="form-control sf-form-control" name="password" type="password" placeholder="Password">
                                            <i class="aon-input-icon fa fa-lock"></i>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label >Confirm Password</label>
                                        <div class="aon-inputicon-box"> 
                                            <input class="form-control sf-form-control" name="password" type="password" placeholder="Confirm Password">
                                            <i class="aon-input-icon fa fa-lock"></i>
                                        </div>
                                    </div>
                                </div>                                        

                                <div class="col-sm-12">
                                    <div class="form-group sign-term-con">
                                        <div class="checkbox sf-radio-checkbox">
                                            <input id="td33" name="abc" value="five" type="checkbox">
                                            <label for="td33">I've read and agree with your <a href="#">Privacy Policy</a> and <a href="#">Terms &amp; Conditions</a> </label>
                                        </div>
                                    </div>
                                </div>  
                                <div class="col-sm-12">
                                    <button type="submit" class="site-button w-100">Submit <i class="feather-arrow-right"></i> </button>
                                </div>                                          
                            </div>
                        </form>
                    </div>
                </div>
                </div>
                 
             </div>
        </div>
        <!-- Search Bar Home END --> 
        
        
    </div>
    <!-- CONTENT END -->


 </div>


{% endblock body %}
    


{% block js %}

{% endblock js %}
    